#!/bin/bash

# Path to the private key file
private_key="~/.ssh/school"

# Server IP address or hostname
server_address="54.157.148.115"

# SSH command using single-character flags
ssh -i "$private_key" ubuntu@"$server_address"

